### ISSUE TITLE
Exception happened during processing of request from ...

### ISSUE THREAD

**Issue by pand0rausa** [SpiderLabs/Responder#56]
I am getting a lot of these errors (every few seconds to once a min). Any suggestions as to what I can do about these errors or if I shouldn't worry about them?

```
Exception happened during processing of request from ('<Redacted IP>', 57628)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/<Redacted Username>/Applications/Windows/Responder/servers/HTTP_Proxy.py", line 214, in handle
    self.__base_handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
```

**Comment by lgandx** [comment]
Should be fixed by now, if not keep updating this issue.
Thanks!

**Comment by pand0rausa** [comment]
Pulled down the latest version and still getting the issue. Received 2 in about 30 sec.

```
----------------------------------------
Exception happened during processing of request from ('\<Redacted IP>', 56796)
Traceback (most recent call last):
  File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
    self.finish_request(request, client_address)
  File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
    self.handle()
  File "/home/\<Redacted user>/Applications/Windows/Responder/servers/HTTP_Proxy.py", line 214, in handle
    self.__base_handle()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 340, in handle
    self.handle_one_request()
  File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
    self.raw_requestline = self.rfile.readline(65537)
  File "/usr/lib/python2.7/socket.py", line 476, in readline
    data = self._sock.recv(self._rbufsize)
error: [Errno 104] Connection reset by peer
----------------------------------------
```
